/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.AdjList;
import org.chocosolver.solver.*;


public class App {
    public static void main(String[] args) {
        Model m = new Model();

        AdjList a02b = new AdjList(m, 5, 6, true, true);

        m.getSolver().printStatistics();
    }
}
